[package]
name = "rs-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
bincode = "1.3.3"
polars = "0.46.0"
pyo3 = "0.24.0"
rand = "0.9.0"
rayon = "1.10.0"
redis = "0.29.2"
serde = "1.0.219"
